version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command:
      [
        "sh",
        "-c",
        "python manage.py collectstatic --noinput && gunicorn file_management_sys.wsgi:application --bind 0.0.0.0:8000",
      ]

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 30696222
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
